spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/feverplans}
spring.datasource.username=${DB_USERNAME:fever}
spring.datasource.password=${DB_PASSWORD:fever}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=always

provider.url=${PROVIDER_URL:https://provider.code-challenge.feverup.com/api/events}
provider.connect-timeout=2s
provider.read-timeout=5s
provider.sync-delay=PT15M
